import 'package:flutter/widgets.dart';

import '../l10n/gen/app_localizations.dart';

/// `context.l` → the generated localizations (EN/ID). Generated by
/// `flutter gen-l10n` (runs automatically on build; see README).
extension L10nX on BuildContext {
  AppLocalizations get l => AppLocalizations.of(this);
}
